name: CI

on:
  push:
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: nix flake check
        run: nix flake check --print-build-logs
